In [117]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text
import numpy as np

In [128]:
engine = create_engine(r'mssql+pyodbc://@USAMA\SQLEXPRESS/inventory?driver=ODBC+Driver+17+for+SQL+Server')

In [121]:
# List all tables in your database
tables = pd.read_sql_query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'", engine)
print(tables)

        TABLE_NAME
0  begin_inventory
1            sales
2  purchase_prices
3        purchases
4   vendor_invoice
5    end_inventory

In [129]:
for table in tables['TABLE_NAME']:
    print('-'*50, f'{table}' ,'-'*50 ) 
    print('COUNT OF RECORDS:', pd.read_sql(f"SELECT COUNT(*) as count FROM dbo.{table}", engine)['count'].values[0])
    display(pd.read_sql(f"SELECT TOP 5 * FROM dbo.{table}",engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
COUNT OF RECORDS: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- sales --------------------------------------------------
COUNT OF RECORDS: 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,12_LEESIDE_17175,12,17175,Beringer Classic Cab Svgn,1.5L,4,27.96,6.99,2024-07-19,1500.0,2,0.90,9819,TREASURY WINE ESTATES
1,12_LEESIDE_17175,12,17175,Beringer Classic Cab Svgn,1.5L,2,13.98,6.99,2024-07-20,1500.0,2,0.45,9819,TREASURY WINE ESTATES
2,12_LEESIDE_17175,12,17175,Beringer Classic Cab Svgn,1.5L,1,6.99,6.99,2024-07-23,1500.0,2,0.22,9819,TREASURY WINE ESTATES
3,12_LEESIDE_17175,12,17175,Beringer Classic Cab Svgn,1.5L,1,6.99,6.99,2024-07-28,1500.0,2,0.22,9819,TREASURY WINE ESTATES
4,12_LEESIDE_17175,12,17175,Beringer Classic Cab Svgn,1.5L,1,6.99,6.99,2024-07-30,1500.0,2,0.22,9819,TREASURY WINE ESTATES

-------------------------------------------------- purchase_prices --------------------------------------------------
COUNT OF RECORDS: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,45535,Citra Pnt Grigio,10.99,1500mL,1500,2,6.57,6785,PALM BAY INTERNATIONAL INC
1,45599,Luigi Bosca RSV Cab Svgn,19.99,750mL,750,2,11.72,9744,FREDERICK WILDMAN & SONS
2,45600,Luigi Bosca La Linda Malbec,10.99,750mL,750,2,7.33,9744,FREDERICK WILDMAN & SONS
3,45605,Bex Rsl Mosel,8.99,750mL,750,2,6.12,9552,M S WALKER INC
4,45647,Masciarelli Rose d'Abruzzo,9.99,750mL,750,2,6.49,10754,PERFECTA WINES

-------------------------------------------------- purchases --------------------------------------------------
COUNT OF RECORDS: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- vendor_invoice --------------------------------------------------
COUNT OF RECORDS: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

-------------------------------------------------- end_inventory --------------------------------------------------
COUNT OF RECORDS: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

In [123]:
purchases = pd.read_sql_query(f"SELECT * FROM purchases WHERE VendorNumber=4466", engine)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,22_SHARNWICK_5255,22,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11540,2024-08-08,2024-08-15,2024-08-24,2024-10-02,9.35,6,56.10,1
1,76_DONCASTER_5215,76,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11540,2024-08-08,2024-08-18,2024-08-24,2024-10-02,9.41,4,37.64,1
2,31_HORNSEY_3140,31,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11540,2024-08-08,2024-08-18,2024-08-24,2024-10-02,11.19,6,67.14,1
3,33_HORNSEY_5255,33,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11540,2024-08-08,2024-08-15,2024-08-24,2024-10-02,9.35,5,46.75,1
4,40_BULLMAR_3140,40,3140,TGI Fridays Orange Dream,1.75L,4466,AMERICAN VINTAGE BEVERAGE,11540,2024-08-08,2024-08-16,2024-08-24,2024-10-02,11.19,6,67.14,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [124]:
purchase_prices = pd.read_sql_query(f"SELECT * FROM purchase_prices WHERE VendorNumber=4466",engine)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [125]:
vendor_invoice = pd.read_sql_query(f"SELECT * FROM vendor_invoice WHERE VendorNumber=4466",engine)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [131]:
sales = pd.read_sql_query(f"SELECT * FROM sales WHERE VendorNO=4466",engine)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,12_LEESIDE_5215,12,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-07-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,12_LEESIDE_5215,12,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-07-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,12_LEESIDE_5215,12,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-07-14,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,12_LEESIDE_5215,12,5215,TGI Fridays Long Island Iced,1.75L,2,25.98,12.99,2024-07-20,1750.0,1,3.67,4466,AMERICAN VINTAGE BEVERAGE
4,12_LEESIDE_5255,12,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-07-14,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [132]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [133]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [46]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [45]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='str')

In [48]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [47]:
sales.groupby('Brand')[['SalesDollars','SalesPrice', 'SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

- The purchases table contains actual purchase data, including date of purchase, products (brands) purchased by the vendor, the amount paid, and the quantity purchased
- The purchase price column is derived from the purchase_prices table, which provides the product wise actual purchase prices. The combination of vendor and brand is unique in this table
- The vendor_invoice table aggregates data from the purchase table, summarizing quantity and dollar amounts, along with an additional column for freight. 
This table maintains uniqueness based on vendor and PO Number
- The sales table captures the actual sales transactions , detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned

-----------------------
As the data that we need for analysis is distributed in different tables, we need to create a summary table containing:

- Purchase transactions made by vendors
- sales transactions data
- freight costs for each vendor
- actual product prices from vendor

In [49]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [56]:
freight_summary = pd.read_sql_query("""
SELECT 
VendorNumber, 
SUM(Freight) as FreightCost
FROM vendor_invoice
Group BY VendorNumber """,engine)

In [57]:
freight_summary

     VendorNumber  FreightCost
0            6830       360.29
1            8920       232.99
2           17032       283.61
3            7749        91.50
4            4692      9139.38
..            ...          ...
121         11567     20964.81
122          2450       251.28
123          7239     16978.67
124          8664     18544.49
125           200         6.19

[126 rows x 2 columns]

In [59]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [68]:
pd.read_sql_query("""
SELECT 
p.VendorName,
p.VendorNumber,
p.Brand,
p.PurchasePrice,
pp.Volume,
pp.Price as ActualPrice,
SUM(p.Quantity) as TotalPurchaseQuantity,
SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p
JOIN purchase_prices pp
ON p.Brand=pp.Brand
Where p.PurchasePrice > 0
GROUP BY p.VendorNumber, p.VendorName,p.Brand, p.PurchasePrice, pp.Volume, pp.Price
ORDER BY TotalPurchaseDollars
""",engine)

,VendorName,VendorNumber,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,PROXIMO SPIRITS INC.,7245,3065,0.71,50,0.99,1,0.71
1,DIAGEO NORTH AMERICA INC,3960,6127,1.47,200,1.99,1,1.47
2,HEAVEN HILL DISTILLERIES,3924,9123,0.74,50,0.99,2,1.48
3,SAZERAC CO INC,8004,5683,0.39,50,0.49,6,2.34
4,WINE GROUP INC,9815,8527,1.32,750,4.99,2,2.64
...,...,...,...,...,...,...,...,...
10687,DIAGEO NORTH AMERICA INC,3960,3545,21.89,1750,29.99,138109,3023206.01
10688,DIAGEO NORTH AMERICA INC,3960,4261,16.17,1750,22.99,201682,3261197.94
10689,PERNOD RICARD USA,17035,8068,18.24,1750,24.99,187407,3418303.68
10690,MARTIGNETTI COMPANIES,4425,3405,23.19,1750,28.99,164038,3804041.22
10691,BROWN-FORMAN CORP,1128,1233,26.27,1750,36.99,145080,3811251.60

In [69]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [ ]:
pd.read_sql_query("""
SELECT
VendorNo,
Brand,
SUM(SalesDollars) as TotalSalesDollars,
SUM(SalesPrice) as TotalSalesPrice,
SUM(SalesQuantity) as TotalSalesQuantity,
SUM(ExciseTax) as TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars
""", engine)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,9.800000e-01,0.98,2,0.10
1,9206,2773,9.900000e-01,0.99,1,0.05
2,3252,3933,1.980000e+00,0.99,2,0.10
3,10050,3623,1.980000e+00,1.98,2,0.10
4,3924,9123,1.980000e+00,0.99,2,0.10
...,...,...,...,...,...,...
11267,3960,3545,4.223108e+06,545778.28,135838,249587.83
11268,3960,4261,4.475973e+06,420050.01,200412,368242.80
11269,17035,8068,4.538121e+06,461140.15,187140,343854.07
11270,4425,3405,4.819073e+06,561512.37,160247,294438.66
11271,1128,1233,5.101920e+06,672819.31,142049,260999.20

In [79]:
vendor_sales_summary= pd.read_sql_query("""
WITH FreightSummary AS(
SELECT 
    VendorNumber, 
    SUM(Freight) as FreightCost
FROM vendor_invoice
Group BY VendorNumber), 


PurchaseSummary AS (
SELECT 
    p.VendorName,
    p.VendorNumber,
    p.Description,
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price as ActualPrice,
    SUM(p.Quantity) as TotalPurchaseQuantity,
    SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p
    JOIN purchase_prices pp
    ON p.Brand=pp.Brand
Where p.PurchasePrice > 0
GROUP BY p.VendorNumber, p.VendorName,p.Brand,p.Description, p.PurchasePrice, pp.Price, pp.Volume 
),

SalesSummary AS (
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) as TotalSalesDollars,
    SUM(SalesPrice) as TotalSalesPrice,
    SUM(SalesQuantity) as TotalSalesQuantity,
    SUM(ExciseTax) as TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand)


SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity,
    ps.TotalPurchaseDollars,
    ss.TotalSalesQuantity,
    ss.TotalSalesDollars,
    ss.TotalSalesPrice,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand= ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber= fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""",engine)

In [80]:
vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2,2.64,5.0,1.595000e+01,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6,2.34,134.0,6.566000e+01,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2,1.48,2.0,1.980000e+00,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1,1.47,72.0,1.432800e+02,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1,0.71,86.0,8.514000e+01,33.66,4.46,38994.78

In [96]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                   float64
TotalPurchaseQuantity      int64
TotalPurchaseDollars     float64
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [112]:
vendor_sales_summary.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
Description              0
PurchasePrice            0
ActualPrice              0
Volume                   0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
FreightCost              0
GrossProfit              0
ProfitMargin             0
StockTurnover            0
SalesToPurchaseRatio     0
dtype: int64

This query generates a vendor-wise sales and purchase summary, which is valuable for:

Performance Optimization:
- The query involves joins and aggregations on large datasets like sales and purchases.
- Storing the pre-aggregated results avoids repeated expensive computations.
- Helps in analyzing sales, purchases, and pricing for different vendors and brands.
- Future Benefits of storing this data for faster Dashboarding and reporting.
- Instead of running expensive queries each time, Dashboard can fetch data quickly from Vendor_Sales_Summary

In [94]:
vendor_sales_summary['VendorName'].unique()

<StringArray>
[          'BROWN-FORMAN CORP',       'MARTIGNETTI COMPANIES',
           'PERNOD RICARD USA',    'DIAGEO NORTH AMERICA INC',
             'BACARDI USA INC',     'JIM BEAM BRANDS COMPANY',
         'MAJESTIC FINE WINES',  'ULTRA BEVERAGE COMPANY LLP',
       'STOLI GROUP,(USA) LLC',        'PROXIMO SPIRITS INC.',
 ...
                    'UNCORKED',         'BRONCO WINE COMPANY',
     'MILTONS DISTRIBUTING CO',                'TRUETT HURST',
         'LAUREATE IMPORTS CO',     'FANTASY FINE WINES CORP',
 'AAPER ALCOHOL & CHEMICAL CO',      'SILVER MOUNTAIN CIDERS',
      'CAPSTONE INTERNATIONAL',          'FLAVOR ESSENCE INC']
Length: 128, dtype: str

In [90]:
vendor_sales_summary['Description'].unique()

<StringArray>
[    'Jack Daniels No 7 Black',       'Tito's Handmade Vodka',
            'Absolut 80 Proof',      'Capt Morgan Spiced Rum',
             'Ketel One Vodka',            'Grey Goose Vodka',
       'Jameson Irish Whiskey',           'Smirnoff Traveler',
                   'Tanqueray',                    'Jim Beam',
 ...
         'Riunite Sweet White',         'Firefly Ridge Chard',
           'Debauchery Pnt Nr', 'Terruzzi & Puthod Vernaccia',
  'Santa Rita Organic Svgn Bl',    'Aresti Pnt Nr Curico Vly',
   'Smirnoff Light Strawberry',           'Crown Royal Apple',
 'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita']
Length: 9651, dtype: str

In [91]:
vendor_sales_summary['Volume'] = vendor_sales_summary['Volume'].astype('float64')

In [92]:
vendor_sales_summary.fillna(0, inplace = True)

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750.0,145080,3811251.60,142049.0,5.101920e+06,672819.31,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750.0,164038,3804041.22,160247.0,4.819073e+06,561512.37,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750.0,187407,3418303.68,187140.0,4.538121e+06,461140.15,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750.0,201682,3261197.94,200412.0,4.475973e+06,420050.01,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750.0,138109,3023206.01,135838.0,4.223108e+06,545778.28,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750.0,2,2.64,5.0,1.595000e+01,10.96,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50.0,6,2.34,134.0,6.566000e+01,1.47,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50.0,2,1.48,2.0,1.980000e+00,0.99,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200.0,1,1.47,72.0,1.432800e+02,77.61,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50.0,1,0.71,86.0,8.514000e+01,33.66,4.46,38994.78

In [93]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [99]:
vendor_sales_summary['GrossProfit'].min()

np.float64(-52002.78000000001)

In [98]:
vendor_sales_summary['GrossProfit'] =  vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [101]:
vendor_sales_summary['ProfitMargin'] =  vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']*100

In [102]:
vendor_sales_summary['StockTurnover'] =  vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [103]:
vendor_sales_summary['SalesToPurchaseRatio'] =  vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [118]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("""
        CREATE TABLE vendor_sales_summary (
            VendorNumber INT,
            VendorName VARCHAR(100),
            Brand INT,
            Description VARCHAR(100),
            PurchasePrice DECIMAL(10,2),
            ActualPrice DECIMAL(10,2),
            Volume DECIMAL(10,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity INT,
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorName,Brand)
        );
    """))
    conn.commit()
    print("Table created successfully!")

ProgrammingError: (pyodbc.ProgrammingError) ('42S01', "[42S01] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'vendor_sales_summary' in the database. (2714) (SQLExecDirectW)")
[SQL:
        CREATE TABLE vendor_sales_summary (
            VendorNumber INT,
            VendorName VARCHAR(100),
            Brand INT,
            Description VARCHAR(100),
            PurchasePrice DECIMAL(10,2),
            ActualPrice DECIMAL(10,2),
            Volume DECIMAL(10,2),
            TotalPurchaseQuantity INT,
            TotalPurchaseDollars DECIMAL(15,2),
            TotalSalesQuantity INT,
            TotalSalesDollars DECIMAL(15,2),
            TotalSalesPrice DECIMAL(15,2),
            TotalExciseTax DECIMAL(15,2),
            FreightCost DECIMAL(15,2),
            GrossProfit DECIMAL(15,2),
            ProfitMargin DECIMAL(15,2),
            StockTurnover DECIMAL(15,2),
            SalesToPurchaseRatio DECIMAL(15,2),
            PRIMARY KEY (VendorName,Brand)
        );
    ]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [110]:
pd.read_sql_query("""
SELECT * FROM vendor_sales_summary""",engine)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, Description, PurchasePrice, ActualPrice, Volume, TotalPurchaseQuantity, TotalPurchaseDollars, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, FreightCost, GrossProfit, ProfitMargin, StockTurnover, SalesToPurchaseRatio]
Index: []

In [114]:
# Replace infinity and NaN values
import numpy as np

# Clean your DataFrame before to_sql()
vendor_sales_summary = vendor_sales_summary.replace([np.inf, -np.inf], 0)
vendor_sales_summary = vendor_sales_summary.fillna(0)

# Then try inserting again
vendor_sales_summary.to_sql('vendor_sales_summary', engine, if_exists='replace', index=False)

20